### ISSUE TITLE
Map Reload Fails

### ISSUE THREAD

**Issue by Dave89rr** [ggcmaps/ggcmaps.github.io#31]
### Description
Switching the parking legend will make the map disappear.

### Recreate:
* Load ggcmaps.com
* Open the menu
* Toggle the parking legend preference

Refreshing the page brings the map back, but when toggling once more the map fails to load again until the next refresh.

**Comment by miked49er** [comment]
Bug resolved. Parking legend toggle was incorrectly implemented. Previous implementation used the addMap function to add the campus map to the view. Now implemented with changeFloor function, ensuring that the campus map is loaded properly.
