### ISSUE TITLE
room D-1100 missing from search

### ISSUE THREAD

**Issue by cengique** [ggcmaps/ggcmaps.github.io#5]
It's supposed to be the circular area at the very bottom of the map.

**Comment by miked49er** [comment]
Do people actually search for D1100?

**Comment by cengique** [comment]
Well, we did. :) I was showing it in class and that was one of the requests. Is that not a proper room?

**Comment by miked49er** [comment]
It is the main lobby for the admissions side of D building, so no it really isn't a proper room.
